version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - MAX_LOCKED_MEMORY=unlimited
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    volumes:
      #- ./config/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - es_data:/usr/share/elasticsearch/data
    expose: ['9200','9206']
    ports: 
      - "9206:9200"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    networks: ['stack']

  #TODO: usar yaml anchors para no repetir
  media_scraper:
    depends_on:
      - elasticsearch
    build: 
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: media-scraper:latest
    environment:
      - ELASTINGA_ELASTICSEARCH_HOST=elasticsearch
      - PROJECT_MODE=Development
    entrypoint: ["bash", "./wait-for-elastic.sh"]
    command: ["python", "-m", "pytest", ]
    networks: ['stack']
volumes:
   esdata:
    driver: local



networks: {stack: {}}

volumes:
  es_data: